Adding defence around duration being missing
https://www.youtube.com/@TheScranLineEveryday/videos right now seems to result in the following exception:
2024-08-27 20:42:24.584 T:3546207   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
												- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
											   Error Type: <class 'KeyError'>
											   Error Contents: 'duration'
											   Traceback (most recent call last):
												 File "/storage/.kodi/addons/plugin.video.ytchannels/default.py", line 4, in <module>
												   ytchannels_main()
												 File "/storage/.kodi/addons/plugin.video.ytchannels/resources/lib/ytchannels.py", line 248, in ytchannels_main
												   video_list=get_latest_from_channel(id, page, filter_shorts == 'true', minimum_duration_in_seconds)
															  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
												 File "/storage/.kodi/addons/plugin.video.ytchannels/resources/lib/functions.py", line 440, in get_latest_from_channel
												   duration = sorted_data[x]['contentDetails']['duration']
															  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
											   KeyError: 'duration'
											   -->End of Python script error report<--


Theory is that it is an "upcoming video"  that is being returned in the API